import './globals.css'
import { Oswald } from "next/font/google"
import styles from "./page.module.css"
import Header from '@/components/Header/Header'
import Footer from '@/components/Footer/Footer'
import { Suspense } from 'react'
import Loading from './dashboard/loading'

const oswald = Oswald({subsets: ["latin"]})
export const metadata = {
  title: 'Home Page Next Js',
  description: 'Generated by create next app',
}

const RootLayout = (props: {

  children: React.ReactNode

}) => {
  return (
    <html className={oswald.className} lang="en">
      <body className={styles.body}>
        <h1>This is a RootLayout</h1>
       <div className={styles.header}> <Header /></div>
        <main className={styles.main}>
          <Suspense fallback={<Loading/>}>
         {props.children}
         </Suspense>
        </main>
           <div className={styles.footer}> <Footer /></div>
        <h1>This is a RootLayout ...todavía</h1>
      </body>
    </html>
  )
}

export default RootLayout;
